### PR TITLE
Improved config + treasure group

### PR DESCRIPTION
**Pull request by wawwior**
might not fit the original intention of the mod, but i like data driven enchantment configuration

### CODE REVIEW

**Comment by DaFuqs** [comment]
Definitely not opposed to having a way to specify enchantments as treasure using the config. It will not match enchantments from mods that do weird stuff (overriding and using `isTreasure() { return false; }`, but that should be a very niche issue and the same that `canAccept()` also has.

Can you add back a default config before merging? While it will not have an effect in this default configuration, it does give modpack creators a starting point and insight how to define exclusivities.

**Comment by wawwior** [comment]
Done :)
Also yes, overriding functions is a bad mixin practice anyway, so i dont think there will be many conflicts.

**Comment by DaFuqs** [comment]
Released for both 1.19+ and 1.19.3 on both Modrinth and Curseforge.
Though wtf are you including that increases the jar size from 13 KB to >4 MB o.O

**Comment by wawwior** [comment]
> Though wtf are you including that increases the jar size from 13 KB to >4 MB o.O

Uh what... im using shadow i guess but its only supposed to shadow a library of mine which is literally smaller than this mod so idk man :c

Looked it up in the repo, the lib is 11.2kb so idk what gradle be packing in that.

**Pull request merged**
